services:
  - type: web
    name: yawscent-indonesia
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node web/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
